Wipe device data
frostsnap/frostsnap pull request #181
Opened 2024-12-06 01:19 UTC by nickfarrow

2024-12-10 08:08 UTC, nickfarrow commented
Ready for review. There is some slightly weird behaviour if you reset a device in a daisy chain - it panics the upstream device, and doesn't get removed from the device list.

2024-12-24 06:14 UTC, LLFourn commented
I don't get the panic. For me the coordinator just never realizes the latter device has reset since it doesn't get error bytes written to it directly. I think you can always just write magic bytes upstream before resetting to fix this -- a better way might be to add an explicit reset signal.

 It would be good if we had a proper modal to indicate you should be looking at the device screen when you need to confirm the data wipe but we can do that later.

2024-12-24 06:20 UTC, LLFourn commented on frostsnapp/lib/device_settings.dart
> +
I think you can just do:

```
deviceListSubject.firstWhere((change) => change.kind == DeviceListChangeKind.Removed);
```

Or something!

2024-12-24 06:21 UTC, LLFourn requested changes
Small dart code optimization otherwise this looks good.

2025-01-07 03:34 UTC, nickfarrow commented on frostsnapp/lib/device_settings.dart
> +
Fixed!

2025-01-09 03:55 UTC, LLFourn commented on frostsnapp/native/src/api.rs
> +    pub fn wipe_device_data(&self, device_id: DeviceId) -> SyncReturn<()> {
I think `SyncReturn<()>` is unnecessary. Is this thing fallible? It should probably return a Stream. I'm guessing this is just keeping it simple for now which is fine as who knows how this turns out after we do some redesigning.

2025-01-09 03:56 UTC, LLFourn approved these changes

2025-01-10 08:49 UTC, merged